const scanBtn = document.getElementById("scanBtn");
const resultDiv = document.getElementById("result");
const aiToggle = document.getElementById("aiToggle");

let currentResponse = null;
let currentLevel = "Trusted";

function setButtonLoading(isLoading) {
  scanBtn.disabled = isLoading;
  scanBtn.innerText = isLoading ? "Scanning..." : "Scan Website";
}

function copyText(text) {
  return navigator.clipboard.writeText(text).catch(() => {
    const area = document.createElement("textarea");
    area.value = text;
    document.body.appendChild(area);
    area.select();
    document.execCommand("copy");
    area.remove();
  });
}

function bindCopyButton(response, level) {
  const btn = document.getElementById("copyBtn");
  if (!btn) return;

  btn.onclick = async () => {
    const text = `Site: ${response.title}\nScore: ${response.score}/100\nStatus: ${level}`;
    await copyText(text);
    btn.innerText = "Copied!";
  };
}

function bindExportButton(response, level) {
  const btn = document.getElementById("exportBtn");
  if (!btn) return;

  btn.onclick = () => {
    const text = `SentinelX Security Report\n\nSite: ${response.title}\nScore: ${response.score}/100\nStatus: ${level}\n\nGenerated by SentinelX`;
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "SentinelX_Report.txt";
    a.click();
    URL.revokeObjectURL(url);
  };
}

function saveHistory(response) {
  chrome.storage?.local.get(["scanHistory"], (data) => {
    let history = data.scanHistory || [];

    history = history.filter((item) => item.site !== response.title);
    history.unshift({
      site: response.title,
      score: response.score,
      time: new Date().toLocaleString(),
    });

    chrome.storage.local.set({ scanHistory: history.slice(0, 10) });
  });
}

function renderHistory() {
  chrome.storage?.local.get(["scanHistory"], (data) => {
    const history = data.scanHistory || [];
    if (!history.length) return;

    const total = history.length;
    const average = Math.round(
      history.reduce((a, b) => a + b.score, 0) / total,
    );
    const risky = history.filter((item) => item.score < 55).length;
    const last = history[0]?.site || "None";

    let html = `
<div class="stats-box">
<strong>📊 SentinelX Stats</strong><br><br>
Total Scans: <strong>${total}</strong><br>
Average Score: <strong>${average}</strong><br>
Risky Sites: <strong>${risky}</strong><br>
Last Site: <strong>${last}</strong>
</div>

<div class="history-box">
<div class="history-head">
<strong>📜 Recent Scans</strong>
<button id="clearHistoryBtn">Clear</button>
</div><br>`;

    history.forEach((item) => {
      html += `
<div class="history-item">
<div>${item.site}</div>
<div><strong>${item.score}/100</strong></div>
</div>`;
    });

    html += "</div>";
    resultDiv.innerHTML += html;

    const clearBtn = document.getElementById("clearHistoryBtn");
    if (clearBtn) {
      clearBtn.onclick = () => {
        chrome.storage.local.set({ scanHistory: [] }, () => {
          document.querySelector(".history-box")?.remove();
          document.querySelector(".stats-box")?.remove();
        });
      };
    }

    bindCopyButton(currentResponse, currentLevel);
    bindExportButton(currentResponse, currentLevel);
  });
}

function getTheme(level) {
  if (level === "Trusted") return { badge: "✅", css: "safe" };
  if (level === "Dangerous") return { badge: "🚨", css: "high" };
  return { badge: "⚠", css: "medium" };
}

function getRecommendation(level) {
  if (level === "Trusted")
    return "Safe Tip: Still verify URLs before entering passwords.";
  if (level === "Dangerous")
    return "Safe Tip: Avoid passwords, payments, or downloads here.";
  return "Safe Tip: Review this page carefully before logging in.";
}

function showLoading() {
  resultDiv.innerHTML = `
<div class="score-box safe">
<strong>🛡 SentinelX Ready</strong><br><br>
Scanning website security signals...
<div class="meter"><div class="meter-fill loading-bar"></div></div>
</div>`;
}

function showUnavailable() {
  resultDiv.innerHTML = `
<div class="score-box medium">
<strong>⚠ Scan Unavailable</strong><br><br>
SentinelX could not fully scan this page.<br><br>
Try refreshing the page or reopening the extension.
</div>`;
}

function renderScan(response) {
  currentResponse = response;
  currentLevel = response.confidenceLabel || "Caution";

  const { badge, css } = getTheme(currentLevel);
  const recommendation = getRecommendation(currentLevel);

  let html = `
<div class="trust-banner ${css}">${badge} ${currentLevel}</div>
<div class="score-box ${css}">
<strong>${response.title}</strong><br><br>
Security Score: ${response.score}/100<br>
Status: ${badge} ${currentLevel}<br><br>
Last Scanned: ${new Date().toLocaleTimeString()}
<div class="meter"><div class="meter-fill" style="width:${response.score}%"></div></div>
</div>
<br><strong>⚠ Detected Risks</strong>`;

  if (!response.findings.length) {
    html += "<p>No major issues found.</p>";
  } else {
    html += "<ul>";
    response.findings.forEach((item) => {
      html += `<li>${item.text} <small>(${item.severity})</small></li>`;
    });
    html += "</ul>";
  }

  html += `
<div class="ai-box"><strong>🤖 AI Insight</strong><br><br>Analyzing threats with SentinelX AI....</div>
<div class="reason-box"><strong>📘 Why This Score</strong><br><br>
${response.score >= 75 ? "✅ No critical threats detected<br>" : ""}
${response.findings.length ? `⚠ ${response.findings.length} risk signals found<br>` : ""}
${response.score < 55 ? "🔴 High caution advised<br>" : ""}
</div>
<div class="recommend-box"><strong>💡 Recommendation</strong><br><br>${recommendation}</div>
<div class="action-row">
<button id="copyBtn">Copy Report</button>
<button id="exportBtn">Export Report</button>
</div>`;

  resultDiv.innerHTML = html;
  bindCopyButton(response, currentLevel);
  bindExportButton(response, currentLevel);
  saveHistory(response);

  return html;
}

async function fetchAI(response, html) {
  if (!aiToggle?.checked) {
    resultDiv.innerHTML = html.replace(
      "Analyzing threats with SentinelX AI....",
      "AI Insights disabled by user.",
    );
    renderHistory();
    return;
  }

  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 6000);

    const res = await fetch("http://localhost:3000/scan", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(response),
      signal: controller.signal,
    });

    clearTimeout(timer);
    const data = await res
      .json()
      .catch(() => ({ explanation: "AI response unavailable right now." }));

    resultDiv.innerHTML = html.replace(
      "Analyzing threats with SentinelX AI....",
      (data.explanation || "AI response unavailable right now.").replace(
        /\n/g,
        "<br>",
      ),
    );
  } catch {
    resultDiv.innerHTML = html.replace(
      "Analyzing threats with SentinelX AI....",
      "AI server unavailable. Scan completed without AI insight.",
    );
  }

  bindCopyButton(currentResponse, currentLevel);
  bindExportButton(currentResponse, currentLevel);
  renderHistory();
}

scanBtn.addEventListener("click", async () => {
  setButtonLoading(true);
  showLoading();

  await new Promise((r) => setTimeout(r, 500));

  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });

  chrome.tabs.sendMessage(tab.id, { type: "SCAN_PAGE" }, async (response) => {
    if (chrome.runtime.lastError || !response) {
      showUnavailable();
      setButtonLoading(false);
      return;
    }

    const html = renderScan(response);
    await fetchAI(response, html);
    setButtonLoading(false);
  });
});
